/*
 * File Name: GenBankRead.java
 * Author: Charles LaCasse 
 */

 /*
  * This program reads a GenBank file and prints out the accession ID, 
  length, 
  and description of the sequence(s) in the file.
  */

 //Import necessary BioJava features 
 import org.biojavax.bio.seq.RichSequence;
 import org.biojavax.bio.seq.RichSequenceIterator;
 import org.biojavax.Namespace;
 import org.biojavax.RichObjectFactory;
 import org.biojava.bio.BioException; 

 //Import necessary Java features 
 import java.io.FileReader;
 import java.io.BufferedReader;
 import java.util.Scanner; 
 import java.io.IOException;



 public class GenBankReadDNA {
    public static void main(String[] args) {

        //Set up the scanner for use in the program for input(s)
        Scanner scanner = new Scanner(System.in);        

        //Ask the user for their name for report generated feature 
        System.out.print("Please enter your name: ");
        System.out.println();
        String userName = scanner.nextLine();

        //Ask the user for the GenBank file they wish to parse
        System.out.print("Please enter the name of the GenBank file you wish to parse: ");
        System.out.println();
        String userFile = scanner.nextLine(); 

        //RichSequenceIterator needs a Buffered Reader so initalize the Buffered reader using the users file from the FileReader
        try (BufferedReader br = new BufferedReader(new FileReader(userFile))) {
            
            //Set up the default Namespace for use in reading the GenBank file
            Namespace ns = RichObjectFactory.getDefaultNamespace();
            
            //Create RichSequenceIterator for reading sequences 
            RichSequenceIterator richSeqIter = RichSequence.IOTools.readGenbankDNA(br, ns);

            //Set a while loop for parsing the entire file
            while (richSeqIter.hasNext()) {
                //Get the next sequence in the file  
                RichSequence richSeq = richSeqIter.nextRichSequence();

                //Parse file for information about 
                String accessionID = richSeq.getAccession();
                Integer length = richSeq.length();
                String description = richSeq.getDescription();

                //Print the accessionID, length, and description on one line with '|' for readability
                System.out.println(accessionID + " | " + length + " (bp) | " + description);
                System.out.println();
                //Print the sequence on another line 
                System.out.println(richSeq.seqString().toUpperCase());
                System.out.println();
            }
            //Print out the report genrrated feature
            System.out.println("Report generated by: " + userName);

        } 
        //Create a file read error message with specific details 
        catch (IOException e) {
            System.err.println("Error! " + e.getMessage());
        } 
        //Create a BioJava error message with specific details 
        catch (BioException e) {
            System.err.println("Error in BioJava! " + e.getMessage());
        } 
        //Close the input scanner 
        finally {
            scanner.close(); 
        }

    }
 }
